#!/bin/bash
# ~/.bashrc

[[ "$-" != *i* ]] && return

PS1='\[\e[31m\]\u\[\e[37m\]@\[\e[31m\]\h \[\e[33m\]\W \[\e[90m\]λ \[\e[39m\]'

HISTFILESIZE=10000
HISTCONTROL='erasedups'
HISTIGNORE=' *:..:~:ls:history:exit:clear:fg:fg *:s reboot:s poweroff'
PROMPT_COMMAND='history -a'
shopt -s histappend
shopt -s autocd

alias g='git'
alias vi='vis'
alias ls='ls --color=auto'
alias lsa='ls -A'
alias imv='nsxiv -a'
alias copy='xclip -se c'
alias wttr='curl wttr.in/Boston?m0'

s(){ su -c "${*@Q}"; }
unlock(){ gpg -q --for-your-eyes-only --no-tty -d "${1}"; }

bash_history_file=$(mktemp "${USER}"_bash_historyXXXXXX)
tac "${HOME}/.bash_history" | awk '!x[$0]++' | tac > "${bash_history_file}"
mv "${bash_history_file}" "${HOME}/.bash_history"
unset bash_history_file
