#!/bin/bash
# ~/.xinitrc

[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

feh --bg-fill --no-fehbg --randomize "/mnt/sinbad/images/wallpapers"
setxkbmap -option caps:super

dt() { echo "$(date +"%a, %b %d")"; }
tm() { echo "$(date +"%I:%M %p")"; }
bt() { cat /sys/class/power_supply/BAT0/capacity; }

while true; do
    xsetroot -name "   $(bt)%   $(dt)   $(tm)   "
    sleep 1
done &

redshift -l 42.5:-71 -b 1.0:0.6 &

searxng-run &

exec dwm
