#!/bin/sh

while read file
do
  case "${1}" in
  "C-x") echo -n "${file}" | xclip -se c ;;
  "C-w") feh --bg-fill --no-fehbg "${file}" ;;
  "C-D") rm "${file}" ; echo "deleted ${file}" ;;
  "C-n") mv -n "${file}" "$(dirname "${file}")/$(dmenu < /dev/null)";;
  esac
done
